import fs from 'node:fs';
const rd = p => JSON.parse(fs.readFileSync(p, 'utf8'));
const a = rd('./office.agents.local.json');
const s = a.seats || a.agents || a;
const list = Array.isArray(s) ? s : Object.values(s);
console.log('seats:', list.length);
const cnt = (k) => { const g = {}; for (const x of list) { const v = x[k] || '-'; g[v] = (g[v] || 0) + 1; } return g; };
console.log('engine:', JSON.stringify(cnt('engine')));
console.log('dept:', JSON.stringify(cnt('dept')));
console.log('withTools:', list.filter(x => Array.isArray(x.tools) && x.tools.length).length);
console.log('sample:', JSON.stringify(list[0]));
const e = rd('./office.engines.json');
console.log('engines:', Object.keys(e.engines || e).join(', '));
console.log('preflight:', JSON.stringify(e.preflight || null));
const c = rd('./office.config.local.json');
console.log('config:', JSON.stringify(c));
