// GENERATED by graph-build.mjs — do not hand-edit. Rebuilt by `node build.mjs` from the configured brain.
// 6 notes · 2 linked · 1 wiki links · 2026-09-09
export const BRAIN = {"notes":6,"nodes":[{"id":"2026-09-09 etsy-seo-yard-mc-uygulamas-fikrini-ele-ve-karar-ver","g":"Agents Office","d":1,"x":0.889,"y":-0.457},{"id":"2026-09-09 etsy-seo-yardimci-uygulamasi-fikrini-ele-ve-karar-ver","g":"Agents Office","d":1,"x":-0.889,"y":0.457}],"links":[[0,1]],"floor":[[0.889,-0.457],[-0.889,0.457]]};
